### ISSUE TITLE
The profile page layout is kinda fucked

### ISSUE THREAD

**Issue by zusorio** [slmnio/slmngg-sfc#258] opened 2024-06-24 17:18 UTC
![image](https://github.com/slmnio/slmngg-sfc/assets/23165606/bad1f11c-95c1-4b85-928d-4385a0a9ef7f)

**Comment by slmnio** [comment] 2024-06-24 17:47
Duplicate of #256 

( 🐢 )

**Comment by zusorio** [comment] 2024-06-24 17:50
Nooooooooooooooooooooooooooooooo not the 🐢

**Comment by slmnio** [comment] 2024-06-24 17:52
hi

**Comment by slmnio** [comment] 2024-06-24 17:52
Duplicate of #256

**Closed by slmnio** 2024-06-24 17:52 UTC
